name: Build Mingw-w64 Toolchain on Ubuntu

on: 
  workflow_dispatch:
  
jobs:
  build-tools:
    name: Build Tools for Mingw-w64
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    strategy:
      matrix:
        thread: [posix]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          chmod +x scripts/download_dep.sh
          ./scripts/download_dep.sh
      
      - name: Mkdir build directory
        run: |
          mkdir -p ${{ github.workspace }}/build/build-temp
          mkdir -p ${{ github.workspace }}/build/ubuntu-tools/mingw64
          mkdir -p ${{ github.workspace }}/build/mingw64
          mkdir -p ${{ github.workspace }}/build/src

      - name: Download source code
        run: |
          chmod +x scripts/download_source.sh
          ./scripts/download_source.sh

      - name: Build gnu dependencies tools
        run: |
          chmod +x gnu_scripts/build_gnu_dep_tools.sh
          ./gnu_scripts/build_gnu_dep_tools.sh
      
      - name: Build gnu binutils
        run: |
          chmod +x gnu_scripts/build_gnu_binutils.sh
          ./gnu_scripts/build_gnu_binutils.sh

      - name: Build gnu gcc stage1
        run: |
          chmod +x gnu_scripts/build_gnu_gcc1.sh
          ./gnu_scripts/build_gnu_gcc1.sh

      - name: Build gnu Mingw64 dependencies
        run: |
          chmod +x gnu_scripts/build_gnu_mingw64.sh
          ./gnu_scripts/build_gnu_mingw64.sh

      - name: Build gnu gcc stage2
        run: |
          chmod +x gnu_scripts/build_gnu_gcc2.sh
          ./gnu_scripts/build_gnu_gcc2.sh
      
      - name: Build mingw dependencies tools
        run: |
          chmod +x mingw64_scripts/build_mingw_dep_tools.sh
          ./mingw64_scripts/build_mingw_dep_tools.sh
      
      - name: Build mingw binutils
        run: |
          chmod +x mingw64_scripts/build_mingw_binutils.sh
          ./mingw64_scripts/build_mingw_binutils.sh

      - name: Build mingw Mingw64 dependencies
        run: |
          chmod +x mingw64_scripts/build_mingw_mingw64.sh
          ./mingw64_scripts/build_mingw_mingw64.sh
      
      - name: Build mingw posix
        if: ${{ matrix.thread == 'posix' }}
        run: |
          chmod +x mingw64_scripts/build_mingw_posix.sh
          ./mingw64_scripts/build_mingw_posix.sh

      - name: Build mingw gcc
        run: |
          chmod +x mingw64_scripts/build_mingw_gcc.sh
          ./mingw64_scripts/build_mingw_gcc.sh
      
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mingw-w64-toolchain
          path: ${{ github.workspace }}/build/mingw64
  
  version-toolchain:
    name: Version Toolchain
    needs: build-tools
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-toolchain

      - name: Version toolchain
        shell: cmd
        run: |
          :: 1. 创建目标目录并解压
          mkdir C:\mingw64
          xcopy /E /I /Y mingw-w64-toolchain\* C:\mingw64\

          :: 2. 把工具链加到 PATH（只对当前 step 生效）
          set PATH=%PATH%;C:\mingw64\bin

          :: 3. 打印版本
          C:\mingw64\bin\x86_64-w64-mingw32-gcc --version
          C:\mingw64\bin\x86_64-w64-mingw32-g++ --version
          C:\mingw64\bin\x86_64-w64-mingw32-ld --version
          


